/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type AlertDefinitionProps = {
  title?: AlertDefinitionTitle;
  message?: AlertDefinitionMessage;
  variant: AlertDefinitionVariant;
};

export type AlertDefinitionTitle = string;

export type AlertDefinitionMessage = string;

export type AlertDefinitionVariant = 'outline' | 'light' | 'filled';
