/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type BaseDefinitionProps = {
  hidden: BaseDefinitionHidden;
  marginBottom: BaseDefinitionMarginBottom;
};

export type BaseDefinitionHidden = boolean;

export type BaseDefinitionMarginBottom = number;
