/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type ImageInputDefinitionProps = {
  value?: ImageInputDefinitionValue;
  disabled?: ImageInputDefinitionDisabled;
  required?: ImageInputDefinitionRequired;
  label?: ImageInputDefinitionLabel;
  helper?: ImageInputDefinitionHelper;
  change?: (payload: ImageInputDefinitionChange) => void;
};

export type ImageInputDefinitionValue = unknown[];

export type ImageInputDefinitionDisabled = boolean;

export type ImageInputDefinitionRequired = boolean;

export type ImageInputDefinitionLabel = string;

export type ImageInputDefinitionHelper = string;

export type ImageInputDefinitionChange = string;
