/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type InputDefinitionProps = {
  type: InputDefinitionType;
  name?: InputDefinitionName;
  placeholder?: InputDefinitionPlaceholder;
  disabled?: InputDefinitionDisabled;
  required?: InputDefinitionRequired;
  hidden?: InputDefinitionHidden;
  label?: InputDefinitionLabel;
  helper?: InputDefinitionHelper;
};

export type InputDefinitionType =
  | 'color'
  | 'date'
  | 'datetime-local'
  | 'email'
  | 'month'
  | 'number'
  | 'password'
  | 'tel'
  | 'text'
  | 'time'
  | 'url'
  | 'week';

export type InputDefinitionName = string;

export type InputDefinitionPlaceholder = string;

export type InputDefinitionDisabled = boolean;

export type InputDefinitionRequired = boolean;

export type InputDefinitionHidden = boolean;

export type InputDefinitionLabel = string;

export type InputDefinitionHelper = string;
