/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type MultipleInputDefinitionProps = {
  value?: MultipleInputDefinitionValue;
  name?: MultipleInputDefinitionName;
  placeholder?: MultipleInputDefinitionPlaceholder;
  disabled?: MultipleInputDefinitionDisabled;
  required?: MultipleInputDefinitionRequired;
  label?: MultipleInputDefinitionLabel;
  helper?: MultipleInputDefinitionHelper;
  change?: (payload: MultipleInputDefinitionChange) => void;
};

export type MultipleInputDefinitionValue = string[];

export type MultipleInputDefinitionName = string;

export type MultipleInputDefinitionPlaceholder = string;

export type MultipleInputDefinitionDisabled = boolean;

export type MultipleInputDefinitionRequired = boolean;

export type MultipleInputDefinitionLabel = string;

export type MultipleInputDefinitionHelper = string;

export type MultipleInputDefinitionChange = string[];
