/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Metadata management
 */
export type AttachmentsSchema = AttachmentSchema[];

export interface AttachmentSchema {
  mime: string;
  path: string;
  size: number;
  name: string;
}
