/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The default value means using platform default database, if set default, the other values will not effective.
 */
export type DataSourceType = 'default' | 'postgres' | 'oracleDB';

/**
 * Describe Data Source Schema
 */
export interface DataSourceSchema {
  $schema?: string;
  connections: {
    [k: string]: DataSourceConnection;
  };
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^(\w)+$".
 */
export interface DataSourceConnection {
  type: DataSourceType;
  host: string;
  port?: number;
  username?: string;
  password?: string;
  database: string;
  schema?: string;
  metadata: string[];
  /**
   * The default value is 30.
   */
  maxPools?: number;
  tablePrefix?: string;
  description?: string;
}
