/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describe Exception Schema
 */
export interface ExceptionSchema {
  names: ExceptionNames;
}

export enum ExceptionNames {
  IsNotArrayException = 'IsNotArrayException',
  IsEmptyArrayException = 'IsEmptyArrayException',
  TypeException = 'TypeException',
  FlowRepeatCountException = 'FlowRepeatCountException',
  FlowNoCompiledCodeException = 'FlowNoCompiledCodeException',
  FlowBadCompileException = 'FlowBadCompileException',
  FlowDefinitionException = 'FlowDefinitionException',
  ElectronValueException = 'ElectronValueException',
  ApiResponseException = 'ApiResponseException',
  SourceDuplicateException = 'SourceDuplicateException',
  SourceUnknownException = 'SourceUnknownException',
  SourceValidateException = 'SourceValidateException',
  SourceNotFoundException = 'SourceNotFoundException',
}
