/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `FlowEventCompiledCodes`'s JSON-Schema definition
 * via the `patternProperty` "^(\w)+$".
 */
export type FlowEventCompiledCode = string;

/**
 * Describe Flow Compiled Codes
 */
export interface FlowCompiledCodes {
  [k: string]: FlowOrgCompiledCodes;
}
/**
 * This interface was referenced by `FlowCompiledCodes`'s JSON-Schema definition
 * via the `patternProperty` "^(\w)+$".
 */
export interface FlowOrgCompiledCodes {
  [k: string]: FlowEventCompiledCodes;
}
/**
 * This interface was referenced by `FlowOrgCompiledCodes`'s JSON-Schema definition
 * via the `patternProperty` "^(\w)+$".
 */
export interface FlowEventCompiledCodes {
  [k: string]: FlowEventCompiledCode;
}
