/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryFilter =
  | {
      [k: string]: QueryFilterExpression;
    }
  | {
      $and: QueryFilter[];
    }
  | {
      $or: QueryFilter[];
    };
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^(\w)+$".
 */
export type QueryFilterExpression =
  | QueryFilterBasicValue
  | {
      $eq?: QueryFilterBasicValue;
      $ne?: QueryFilterBasicValue;
      $gt?: QueryFilterBasicValue;
      $gte?: QueryFilterBasicValue;
      $lt?: QueryFilterBasicValue;
      $lte?: QueryFilterBasicValue;
      $in?: QueryFilterBasicValue[];
      $and?: QueryFilter[];
      $or?: QueryFilter[];
      /**
       * The results are in foreign ids.
       */
      $foreign?:
        | {
            [k: string]: QueryFilterExpression;
          }
        | {
            $and: QueryFilter[];
          }
        | {
            $or: QueryFilter[];
          };
      /**
       * The results are like this value with no case sensitive.
       */
      $like?: string;
    };
export type QueryFilterBasicValue = string | number | boolean;

/**
 * Describe HTTP Request Incoming Payload
 */
export interface HttpQuerySchema {
  filter?: QueryFilter;
  select?: {
    /**
     * The style is like MongoDB.
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(\w)+$".
     */
    [k: string]: boolean;
  };
  sort?: {
    /**
     * The style is like MongoDB.
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(\w)+$".
     */
    [k: string]: 'asc' | 'desc';
  };
  limit?: number;
  skip?: number;
  count?: boolean;
}
