/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describe HTTP Request Incoming Payload
 */
export interface HttpQuerySchema {
  /**
   * The filter should be validate by custom program.
   */
  filter?: {
    [k: string]: unknown;
  };
  select?: {
    /**
     * The style is like MongoDB.
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(\w)+$".
     */
    [k: string]: boolean;
  };
  sort?: {
    /**
     * The style is like MongoDB.
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(\w)+$".
     */
    [k: string]: 'asc' | 'desc';
  };
  limit?: number;
  skip?: number;
  count?: boolean;
}
