/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^(\w)+$".
 */
export type PlayerRepository =
  | PlayerRepositoryForm
  | PlayerRepositorySourceQuery
  | PlayerRepositoryTransformer;
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^(\w)+$".
 */
export type PlayerEvent =
  | PlayerEventSetRepository
  | PlayerEventTriggerRepository;

/**
 * Define the player contained Stores and UI Elements
 */
export interface PlayerSchema {
  title: string;
  entry: string;
  containers: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(\w)+$".
     */
    [k: string]: {
      repositories: {
        [k: string]: PlayerRepository;
      };
      events: {
        [k: string]: PlayerEvent;
      };
      widgets: {
        [k: string]: PlayerWidget;
      };
      root: string[];
      tree: {
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^(\w)+$".
         */
        [k: string]: string[];
      };
    };
  };
}
export interface PlayerRepositoryForm {
  type: 'Form';
  states: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(\w)+$".
     */
    [k: string]: {
      [k: string]: unknown;
    };
  };
  [k: string]: unknown;
}
export interface PlayerRepositorySourceQuery {
  type: 'SourceQuery';
  atomName: string;
  query: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface PlayerRepositoryTransformer {
  type: 'Transformer';
  func: string;
  [k: string]: unknown;
}
export interface PlayerEventSetRepository {
  action: 'setRepository';
  target: string;
  path: string[];
  value: string;
  [k: string]: unknown;
}
export interface PlayerEventTriggerRepository {
  action: 'triggerRepository';
  target: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^(\w)+$".
 */
export interface PlayerWidget {
  tag: string;
  states: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(\w)+$".
     */
    [k: string]: string;
  };
  events: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(\w)+$".
     */
    [k: string]: string[];
  };
}
