/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `PlayerFetches`'s JSON-Schema definition
 * via the `patternProperty` "^(\w)+$".
 */
export type PlayerFetch = PlayerFetchSourceQuery;

/**
 * Define the player contained Stores and UI Elements
 */
export interface PlayerSchema {
  localStorage?: unknown;
  theme?: unknown;
  router?: unknown;
  fetches: PlayerFetches;
  pages: PlayerPages;
}
export interface PlayerFetches {
  [k: string]: PlayerFetch;
}
export interface PlayerFetchSourceQuery {
  type?: 'SourceQuery';
  atomName?: string;
  query?: {
    /**
     * The filter should be validate by custom program.
     */
    filter?: {
      [k: string]: unknown;
    };
    select?: {
      /**
       * The style is like MongoDB.
       *
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^(\w)+$".
       */
      [k: string]: boolean;
    };
    sort?: {
      /**
       * The style is like MongoDB.
       *
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^(\w)+$".
       */
      [k: string]: 'asc' | 'desc';
    };
    limit?: number;
    skip?: number;
    count?: boolean;
  };
  [k: string]: unknown;
}
export interface PlayerPages {
  [k: string]: PlayerPage;
}
/**
 * This interface was referenced by `PlayerPages`'s JSON-Schema definition
 * via the `patternProperty` "^(\w)+$".
 */
export interface PlayerPage {
  elements?: unknown;
  tree?: unknown;
  lifecycle?: unknown;
  [k: string]: unknown;
}
