/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type _InternalTaskReference =
  | boolean
  | {
      $id?: string;
      $schema?: string;
      $ref?: string;
      $comment?: string;
      title?: string;
      description?: string;
      items?:
        | _InternalTaskReference
        | [_InternalTaskReference, ..._InternalTaskReference[]];
      required?: string[];
      additionalProperties?: _InternalTaskReference;
      definitions?: {
        [k: string]: _InternalTaskReference;
      };
      properties?: {
        [k: string]: _InternalTaskReference;
      };
      patternProperties?: {
        [k: string]: _InternalTaskReference;
      };
      const?: true;
      enum?: [true, ...unknown[]];
      type?:
        | 'array'
        | 'boolean'
        | 'integer'
        | 'null'
        | 'number'
        | 'object'
        | 'string';
      [k: string]: unknown;
    };

/**
 * Define the connector task definitions
 */
export interface TaskSchema {
  $schema?: string;
  scope: 'internal' | 'resource';
  address?: string;
  withAccessToken: boolean;
  protocol?: 'http';
  parameters: {
    [k: string]: TaskParameter;
  };
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^(.)+$".
 */
export interface TaskParameter {
  schema: _InternalTaskReference;
  required: boolean;
  editorType:
    | 'taskName'
    | 'atomName'
    | 'sourceQuery'
    | 'connectorName'
    | 'parallelBranches'
    | 'choiceConditions'
    | 'repeatCount'
    | 'template'
    | 'description';
}
