/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Define the presenter contained Stores and UI Elements
 */
export interface WidgetSchema {
  $schema?: string;
  tag: string;
  icon?: string;
  experimental?: boolean;
  allowedChildTags?: string[];
  searchKeywords?: string[];
  properties: {
    [k: string]: WidgetProperty;
  };
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^(\w)+$".
 */
export interface WidgetProperty {
  label: string;
  type:
    | 'string'
    | 'integer'
    | 'number'
    | 'boolean'
    | 'void'
    | 'enum'
    | 'stringArray'
    | 'optionArray'
    | 'unknownObject'
    | 'unknownArray'
    | 'dataBinding'
    | 'breakpoints'
    | 'attachments'
    | 'boxModel'
    | 'multipleState';
  enums?: string[];
  disabledJsMode?: boolean;
  isEvent?: boolean;
  placeholder?: string;
  description?: string;
}
