import { CustomVariables } from './variables';

export const lightTheme: Record<CustomVariables, string> = {
  // Basic
  [CustomVariables.generalFont]:
    'system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
  [CustomVariables.codeFont]:
    'SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  [CustomVariables.codeColor]: '#d63384',
  [CustomVariables.fontSize]: '1rem',
  [CustomVariables.fontWeight]: '400',
  [CustomVariables.lineHeight]: '1.5',
  [CustomVariables.bodyColor]: '#212529',
  [CustomVariables.bodyTextAlign]: 'left',
  [CustomVariables.bodyBg]: '#fff',
  [CustomVariables.emphasisColor]: '#000',
  [CustomVariables.highlightBg]: '#fff3cd',
  [CustomVariables.linkColor]: '#0d6efd',
  [CustomVariables.linkDecoration]: 'underline',
  [CustomVariables.linkHoverColor]: '#0a58ca',
  // Buttons
  [CustomVariables.primary]: '#0d6efd',
  [CustomVariables.primaryBgSubtle]: '#cfe2ff',
  [CustomVariables.primaryBorderSubtle]: '#9ec5fe',
  [CustomVariables.primaryText]: '#0a58ca',
  [CustomVariables.secondary]: '#6c757d',
  [CustomVariables.secondaryBgSubtle]: '#f8f9fa',
  [CustomVariables.secondaryBorderSubtle]: '#e9ecef',
  [CustomVariables.secondaryText]: '#6c757d',
  [CustomVariables.success]: '#198754',
  [CustomVariables.successBgSubtle]: '#d1e7dd',
  [CustomVariables.successBorderSubtle]: '#a3cfbb',
  [CustomVariables.successText]: '#146c43',
  [CustomVariables.danger]: '#dc3545',
  [CustomVariables.dangerBgSubtle]: '#f8d7da',
  [CustomVariables.dangerBorderSubtle]: '#f1aeb5',
  [CustomVariables.dangerText]: '#b02a37',
  [CustomVariables.warning]: '#ffc107',
  [CustomVariables.warningBgSubtle]: '#fff3cd',
  [CustomVariables.warningBorderSubtle]: '#ffe69c',
  [CustomVariables.warningText]: '#997404',
  [CustomVariables.info]: '#0dcaf0',
  [CustomVariables.infoBgSubtle]: '#cff4fc',
  [CustomVariables.infoBorderSubtle]: '#9eeaf9',
  [CustomVariables.infoText]: '#087990',
  // Border
  [CustomVariables.borderWidth]: '1px',
  [CustomVariables.borderStyle]: 'solid',
  [CustomVariables.borderColor]: '#dee2e6',
  [CustomVariables.borderRadius]: '0.375rem',
  // Breakpoint
  [CustomVariables.breakpointXs]: '0',
  [CustomVariables.breakpointSm]: '576px',
  [CustomVariables.breakpointMd]: '768px',
  [CustomVariables.breakpointLg]: '992px',
  [CustomVariables.breakpointXl]: '1200px',
  [CustomVariables.breakpointXxl]: '1400px',
  // Space
  [CustomVariables.spaceXs]: '4px',
  [CustomVariables.spaceSm]: '8px',
  [CustomVariables.spaceMd]: '12px',
  [CustomVariables.spaceLg]: '16px',
  [CustomVariables.spaceXl]: '20px',
  // Radius
  [CustomVariables.radius]: '2px',
};

//   '--sk-blue': '#0d6efd',
//   '--sk-indigo': '#6610f2',
//   '--sk-purple': '#6f42c1',
//   '--sk-pink': '#d63384',
//   '--sk-red': '#dc3545',
//   '--sk-orange': '#fd7e14',
//   '--sk-yellow': '#ffc107',
//   '--sk-green': '#198754',
//   '--sk-teal': '#20c997',
//   '--sk-cyan': '#0dcaf0',
//   '--sk-black': '#000',
//   '--sk-white': '#fff',
//   '--sk-gray': '#6c757d',
//   '--sk-gray-dark': '#343a40',
//   '--sk-gray-100': '#f8f9fa',
//   '--sk-gray-200': '#e9ecef',
//   '--sk-gray-300': '#dee2e6',
//   '--sk-gray-400': '#ced4da',
//   '--sk-gray-500': '#adb5bd',
//   '--sk-gray-600': '#6c757d',
//   '--sk-gray-700': '#495057',
//   '--sk-gray-800': '#343a40',
//   '--sk-gray-900': '#212529',
//   '--sk-primary': '#0d6efd',
//   '--sk-secondary': '#6c757d',
//   '--sk-success': '#198754',
//   '--sk-info': '#0dcaf0',
//   '--sk-warning': '#ffc107',
//   '--sk-danger': '#dc3545',
//   '--sk-light': '#f8f9fa',
//   '--sk-dark': '#212529',
//   '--sk-primary-rgb': '13, 110, 253',
//   '--sk-secondary-rgb': '108, 117, 125',
//   '--sk-success-rgb': '25, 135, 84',
//   '--sk-info-rgb': '13, 202, 240',
//   '--sk-warning-rgb': '255, 193, 7',
//   '--sk-danger-rgb': '220, 53, 69',
//   '--sk-light-rgb': '248, 249, 250',
//   '--sk-dark-rgb': '33, 37, 41',
//   '--sk-primary-text': '#0a58ca',
//   '--sk-secondary-text': '#6c757d',
//   '--sk-success-text': '#146c43',
//   '--sk-info-text': '#087990',
//   '--sk-warning-text': '#997404',
//   '--sk-danger-text': '#b02a37',
//   '--sk-light-text': '#6c757d',
//   '--sk-dark-text': '#495057',
//   '--sk-primary-bg-subtle': '#cfe2ff',
//   '--sk-secondary-bg-subtle': '#f8f9fa',
//   '--sk-success-bg-subtle': '#d1e7dd',
//   '--sk-info-bg-subtle': '#cff4fc',
//   '--sk-warning-bg-subtle': '#fff3cd',
//   '--sk-danger-bg-subtle': '#f8d7da',
//   '--sk-light-bg-subtle': '#fcfcfd',
//   '--sk-dark-bg-subtle': '#ced4da',
//   '--sk-primary-border-subtle': '#9ec5fe',
//   '--sk-secondary-border-subtle': '#e9ecef',
//   '--sk-success-border-subtle': '#a3cfbb',
//   '--sk-info-border-subtle': '#9eeaf9',
//   '--sk-warning-border-subtle': '#ffe69c',
//   '--sk-danger-border-subtle': '#f1aeb5',
//   '--sk-light-border-subtle': '#e9ecef',
//   '--sk-dark-border-subtle': '#adb5bd',
//   '--sk-white-rgb': '255, 255, 255',
//   '--sk-black-rgb': '0, 0, 0',
//   '--sk-body-color-rgb': '33, 37, 41',
//   '--sk-body-bg-rgb': '255, 255, 255',
//   '--sk-font-sans-serif':
//     'system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
//   '--sk-font-monospace':
//     'SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
//   '--sk-gradient':
//     'linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))',
//   '--sk-body-font-family': 'var(--sk-font-sans-serif)',
//   '--sk-body-font-size': '1rem',
//   '--sk-body-font-weight': '400',
//   '--sk-body-line-height': '1.5',
//   '--sk-body-color': '#212529',
//   '--sk-emphasis-color': '#000',
//   '--sk-emphasis-color-rgb': '0, 0, 0',
//   '--sk-secondary-color': 'rgba(33, 37, 41, 0.75)',
//   '--sk-secondary-color-rgb': '33, 37, 41',
//   '--sk-secondary-bg': '#e9ecef',
//   '--sk-secondary-bg-rgb': '233, 236, 239',
//   '--sk-tertiary-color': 'rgba(33, 37, 41, 0.5)',
//   '--sk-tertiary-color-rgb': '33, 37, 41',
//   '--sk-tertiary-bg': '#f8f9fa',
//   '--sk-tertiary-bg-rgb': '248, 249, 250',
//   '--sk-body-bg': '#fff',
//   '--sk-link-color': '#0d6efd',
//   '--sk-link-color-rgb': '13, 110, 253',
//   '--sk-link-decoration': 'underline',
//   '--sk-link-hover-color': '#0a58ca',
//   '--sk-link-hover-color-rgb': '10, 88, 202',
//   '--sk-code-color': '#d63384',
//   '--sk-highlight-bg': '#fff3cd',
//   '--sk-border-width': '1px',
//   '--sk-border-style': 'solid',
//   '--sk-border-color': '#dee2e6',
//   '--sk-border-color-translucent': 'rgba(0, 0, 0, 0.175)',
//   '--sk-border-radius': '0.375rem',
//   '--sk-border-radius-sm': '0.25rem',
//   '--sk-border-radius-lg': '0.5rem',
//   '--sk-border-radius-xl': '1rem',
//   '--sk-border-radius-2xl': '2rem',
//   '--sk-border-radius-pill': '50rem',
//   '--sk-box-shadow': '0 0.5rem 1rem rgba(var(--sk-body-color-rgb), 0.15)',
//   '--sk-box-shadow-sm':
//     '0 0.125rem 0.25rem rgba(var(--sk-body-color-rgb), 0.075)',
//   '--sk-box-shadow-lg': '0 1rem 3rem rgba(var(--sk-body-color-rgb), 0.175)',
//   '--sk-box-shadow-inset':
//     'inset 0 1px 2px rgba(var(--sk-body-color-rgb), 0.075)',
//   '--sk-form-control-bg': 'var(--sk-body-bg)',
//   '--sk-form-control-disabled-bg': 'var(--sk-secondary-bg)',
//   '--sk-breakpoint-xs': '0',
//   '--sk-breakpoint-sm': '576px',
//   '--sk-breakpoint-md': '768px',
//   '--sk-breakpoint-lg': '992px',
//   '--sk-breakpoint-xl': '1200px',
//   '--sk-breakpoint-xxl': '1400px',
