export enum CustomVariables {
  generalFont = '--sk-generalFont',
  codeFont = '--sk-codeFont',
  codeColor = '--sk-codeColor',
  fontSize = '--sk-fontSize',
  fontWeight = '--sk-fontWeight',
  lineHeight = '--sk-lineHeight',
  bodyColor = '--sk-bodyColor',
  bodyTextAlign = '--sk-bodyTextAlign',
  bodyBg = '--sk-bodyBg',
  emphasisColor = '--sk-emphasisColor',
  highlightBg = '--sk-highlightBg',
  linkColor = '--sk-linkColor',
  linkDecoration = '--sk-linkDecoration',
  linkHoverColor = '--sk-linkHoverColor',

  primary = '--sk-primary',
  primaryBgSubtle = '--sk-primaryBgSubtle',
  primaryBorderSubtle = '--sk-primaryBorderSubtle',
  primaryText = '--sk-primaryText',

  secondary = '--sk-secondary',
  secondaryBgSubtle = '--sk-secondaryBgSubtle',
  secondaryBorderSubtle = '--sk-secondaryBorderSubtle',
  secondaryText = '--sk-secondaryText',

  success = '--sk-success',
  successBgSubtle = '--sk-successBgSubtle',
  successBorderSubtle = '--sk-successBorderSubtle',
  successText = '--sk-successText',

  danger = '--sk-danger',
  dangerBgSubtle = '--sk-dangerBgSubtle',
  dangerBorderSubtle = '--sk-dangerBorderSubtle',
  dangerText = '--sk-dangerText',

  warning = '--sk-warning',
  warningBgSubtle = '--sk-warningBgSubtle',
  warningBorderSubtle = '--sk-warningBorderSubtle',
  warningText = '--sk-warningText',

  info = '--sk-info',
  infoBgSubtle = '--sk-infoBgSubtle',
  infoBorderSubtle = '--sk-infoBorderSubtle',
  infoText = '--sk-infoText',

  borderWidth = '--sk-borderWidth',
  borderStyle = '--sk-borderStyle',
  borderColor = '--sk-borderColor',
  borderRadius = '--sk-borderRadius',

  breakpointXs = '--sk-breakpointXs',
  breakpointSm = '--sk-breakpointSm',
  breakpointMd = '--sk-breakpointMd',
  breakpointLg = '--sk-breakpointLg',
  breakpointXl = '--sk-breakpointXl',
  breakpointXxl = '--sk-breakpointXxl',

  spaceXs = '--sk-spaceXs',
  spaceSm = '--sk-spaceSm',
  spaceMd = '--sk-spaceMd',
  spaceLg = '--sk-spaceLg',
  spaceXl = '--sk-spaceXl',

  radius = '--sk-radius',
}
