import { INestApplication } from '@nestjs/common';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';

export function createApiCenter(app: INestApplication) {
  const config = new DocumentBuilder()
    .setTitle('Shukun Platform API Center')
    .setDescription(
      'These APIs was generated by Shukun Server. The APIs is not relevant with business logic, you should orchestrate source and webhook APIs for your business. PS: do not use the deprecated APIs, these APIs will be removed anytime. If you want to know how to filter the result or select returns, you can check out this manual: https://www.npmjs.com/package/mongoose-query-parser .',
    )
    .addBearerAuth()
    .build();
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('apis-center', app, document);
}
