import { INestApplication } from '@nestjs/common';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';

export function createApiCenter(app: INestApplication) {
  const config = new DocumentBuilder()
    .setTitle('Shukun Platform API Center')
    .setDescription(
      'These APIs was generated by Shukun Server. The APIs is not relevant with business logic, you should orchestrate source and webhook APIs for your business.',
    )
    .addBearerAuth()
    .build();
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('apis-center', app, document);
}
