export enum StoreNames {
  Global = 'Global',
  Table = 'Table',
  Detail = 'Detail',
  Reference = 'Reference',
  Search = 'Search',
  Session = 'Session',
  Metadata = 'Metadata',
  View = 'View',
  Source = 'Source',
  Role = 'Role',
  Security = 'Security',
  CustomModal = 'CustomModal',
  Router = 'Router',
}
