/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Define the presenter contained Stores and UI Elements
 */
export interface WidgetSchema {
  $schema?: string;
  tag: string;
  experimental?: boolean;
  properties: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(\w)+$".
     */
    [k: string]: {
      type:
        | 'string'
        | 'number'
        | 'boolean'
        | 'array'
        | 'object'
        | 'callback'
        | 'enum';
      label: string;
      defaultValue?: string;
      enumOptions?: {
        label: string;
        value: string;
      }[];
    };
  };
}
