import { extractAtom } from './helpers/extract-atom';
import { extractElectronOptions } from './helpers/extract-electron-options';
import { extractMetadataToTypes } from './helpers/extract-metadata';
import { extractShard } from './helpers/extract-shared';
import { readApplication } from './helpers/read-application';
import { writeFile } from './helpers/write-file';
import { format, Options as FormatOptions } from 'prettier';

export interface TypeGeneratorOptions {
  inputFile: string;
  outputFile: string;
  style?: FormatOptions;
  bannerComment?: string;
}

export async function typeGenerator({
  inputFile,
  outputFile,
  style,
  bannerComment = '/* eslint-disable */\n/* tslint:disable */\n/**\n* This file was automatically generated by SHUKUN json-schema.\n*/',
}: TypeGeneratorOptions) {
  const application = await readApplication(inputFile);

  let text = '';
  text += bannerComment;
  text += '\n';
  text += extractShard();
  text += extractMetadataToTypes(
    application,
    extractAtom,
    extractElectronOptions,
  );

  const formattedText = format(text, { ...style, parser: 'babel' });

  await writeFile(formattedText, outputFile);
}
