import { Options } from 'prettier';

export type TypeGeneratorOptions = {
  style?: Options;
  bannerComment?: string;
};

export const DEFAULT_BANNER_COMMENT =
  '/* eslint-disable */\n/* tslint:disable */\n/**\n* This file was automatically generated by SHUKUN json-schema.\n*/';
