import { ApplicationSchema } from '@shukun/schema';

import { TypeGenerator } from './type-generator';
import lowCode from './type-generator.mock.json';

describe('TypeGenerator', () => {
  const trimCode = (code: string) => {
    return code
      .trim()
      .split('\n')
      .map((item) => item.trim());
  };

  describe('generate', () => {
    it('should pass, when generate metadata types.', () => {
      const types = new TypeGenerator().generate(lowCode as ApplicationSchema);
      expect(trimCode(types)).toEqual(
        trimCode(
          `
        /**
         * This file was automatically generated by SHUKUN json-schema.
         */
        import { AttachmentSchema } from "@shukun/schema";
        export type IDString = string;
        export type DateTimeIsoString = string;
        export type AtomAModel = {
          _id: IDString;
          owner?: IDString;
          createdAt?: DateTimeIsoString;
          updatedAt?: DateTimeIsoString;
          text?: string;
          nameText?: string;
          largeText?: string;
          singleSelect?: "test" | "test2" | "test3";
          multiSelect?: ("test" | "test2" | "test3")[];
          boolean?: boolean;
          dateTime?: DateTimeIsoString;
          integer?: number;
          float?: number;
          currency?: number;
          password?: string;
          manyToMany?: IDString[];
          manyToOne?: IDString;
          attachment?: AttachmentSchema[];
          mixed?: unknown;
          role?: IDString[];
        };
        export const AtomASingleSelectOptions = {
          test: "test",
          test2: "test2",
          test3: "test3",
        };
        export const AtomAMultiSelectOptions = {
          test: "test",
          test2: "test2",
          test3: "test3",
        };
        export type AtomBModel = {
          _id: IDString;
          owner?: IDString;
          createdAt?: DateTimeIsoString;
          updatedAt?: DateTimeIsoString;
          number: string;
        };
    `,
        ),
      );
    });
  });
});
