import { ApplicationSchema } from '@shukun/schema';

import { extractAtom } from './helpers/extract-atom';
import { extractElectronOptions } from './helpers/extract-electron-options';
import { extractMetadataToTypes } from './helpers/extract-metadata';
import { extractShard } from './helpers/extract-shared';
import { TypeGeneratorOptions } from './type.generator.type';

export class TypeGenerator {
  private DEFAULT_BANNER_COMMENT =
    '/**\n* This file was automatically generated by SHUKUN json-schema.\n*/';

  generate(lowCode: ApplicationSchema, options?: TypeGeneratorOptions) {
    let text = '';
    text += options?.bannerComment ?? this.DEFAULT_BANNER_COMMENT;
    text += '\n';
    text += extractShard();
    text += extractMetadataToTypes(
      lowCode,
      extractAtom,
      extractElectronOptions,
    );

    return text;
  }
}
