import { WidgetSchema } from '@shukun/schema';

import {
  inputDefinition,
  imageInputDefinition,
  multipleInputDefinition,
  textDefinition,
  codeDefinition,
  buttonDefinition,
  listDefinition,
  selectDefinition,
  boxDefinition,
  navLinkDefinition,
  tableDefinition,
  formDefinition,
  searchFormDefinition,
  gridDefinition,
  alertDefinition,
  radioSelectDefinition,
  checkboxSelectDefinition,
  cardDefinition,
  badgeDefinition,
  booleanSelectDefinition,
  numberInputDefinition,
} from './definitions';

export const webWidgetDefinitions: Record<string, WidgetSchema> = {
  'sk-input': inputDefinition,
  'sk-image-input': imageInputDefinition,
  'sk-multiple-input': multipleInputDefinition,
  'sk-text': textDefinition,
  'sk-code': codeDefinition,
  'sk-button': buttonDefinition,
  'sk-list': listDefinition,
  'sk-select': selectDefinition,
  'sk-box': boxDefinition,
  'sk-nav-link': navLinkDefinition,
  'sk-table': tableDefinition,
  'sk-form': formDefinition,
  'sk-search-form': searchFormDefinition,
  'sk-grid': gridDefinition,
  'sk-alert': alertDefinition,
  'sk-radio-select': radioSelectDefinition,
  'sk-checkbox-select': checkboxSelectDefinition,
  'sk-card': cardDefinition,
  'sk-badge': badgeDefinition,
  'sk-boolean-select': booleanSelectDefinition,
  'sk-number-input': numberInputDefinition,
};
