export const fieldTypeOptions = [
  { label: '文字', value: 'Text' },
  { label: '标识符', value: 'NameText' },
  { label: '段落', value: 'LargeText' },
  { label: '单选', value: 'SingleSelect' },
  { label: '多选', value: 'MultiSelect' },
  { label: '布尔', value: 'Boolean' },
  { label: '日期时间', value: 'DateTime' },
  { label: '整数', value: 'Integer' },
  { label: '浮点数', value: 'Float' },
  { label: '货币', value: 'Currency' },
  { label: '密码', value: 'Password' },
  { label: '多对多', value: 'ManyToMany' },
  { label: '多对一', value: 'ManyToOne' },
  { label: '创建人', value: 'Owner' },
  { label: '附件或图片', value: 'Attachment' },
  { label: 'JSON', value: 'Mixed' },
  { label: '角色', value: 'Role' },
  { label: '一对多', value: 'OneToMany' },
  { label: '链接文本', value: 'LinkText' },
];
