/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type BadgeDefinitionProps = {
  value?: BadgeDefinitionValue;
  variant: BadgeDefinitionVariant;
  color?: BadgeDefinitionColor;
};

export type BadgeDefinitionValue = string;

export type BadgeDefinitionVariant =
  | 'outline'
  | 'light'
  | 'filled'
  | 'gradient'
  | 'dot';

export type BadgeDefinitionColor = string;
