/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type BooleanSelectDefinitionProps = {
  name?: BooleanSelectDefinitionName;
  disabled?: BooleanSelectDefinitionDisabled;
  required?: BooleanSelectDefinitionRequired;
  label?: BooleanSelectDefinitionLabel;
  helper?: BooleanSelectDefinitionHelper;
};

export type BooleanSelectDefinitionName = string;

export type BooleanSelectDefinitionDisabled = boolean;

export type BooleanSelectDefinitionRequired = boolean;

export type BooleanSelectDefinitionLabel = string;

export type BooleanSelectDefinitionHelper = string;
