/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type BoxDefinitionProps = {
  orientation: BoxDefinitionOrientation;
  paddingTop: BoxDefinitionPaddingTop;
  paddingRight: BoxDefinitionPaddingRight;
  paddingBottom: BoxDefinitionPaddingBottom;
  paddingLeft: BoxDefinitionPaddingLeft;
  marginTop: BoxDefinitionMarginTop;
  marginRight: BoxDefinitionMarginRight;
  marginBottom: BoxDefinitionMarginBottom;
  marginLeft: BoxDefinitionMarginLeft;
  height: BoxDefinitionHeight;
};

export type BoxDefinitionOrientation = 'horizontal' | 'vertical';

export type BoxDefinitionPaddingTop = number;

export type BoxDefinitionPaddingRight = number;

export type BoxDefinitionPaddingBottom = number;

export type BoxDefinitionPaddingLeft = number;

export type BoxDefinitionMarginTop = number;

export type BoxDefinitionMarginRight = number;

export type BoxDefinitionMarginBottom = number;

export type BoxDefinitionMarginLeft = number;

export type BoxDefinitionHeight = number;
