/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type BoxDefinitionProps = {
  orientation: BoxDefinitionOrientation;
  paddingTop: BoxDefinitionPaddingTop;
  paddingRight: BoxDefinitionPaddingRight;
  paddingBottom: BoxDefinitionPaddingBottom;
  paddingLeft: BoxDefinitionPaddingLeft;
};

export type BoxDefinitionOrientation = 'horizontal' | 'vertical';

export type BoxDefinitionPaddingTop = number;

export type BoxDefinitionPaddingRight = number;

export type BoxDefinitionPaddingBottom = number;

export type BoxDefinitionPaddingLeft = number;
