/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

import { ReactNode } from 'React';

export type BoxDefinitionProps = {
  orientation: 'horizontal' | 'vertical';
  paddingTop?: number;
  paddingRight?: number;
  paddingBottom?: number;
  paddingLeft?: number;
  children?: ReactNode;
};
