/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type CheckboxSelectDefinitionProps = {
  value?: CheckboxSelectDefinitionValue;
  values?: CheckboxSelectDefinitionValues;
  labels?: CheckboxSelectDefinitionLabels;
  disabled?: CheckboxSelectDefinitionDisabled;
  required?: CheckboxSelectDefinitionRequired;
  hidden?: CheckboxSelectDefinitionHidden;
  label?: CheckboxSelectDefinitionLabel;
  helper?: CheckboxSelectDefinitionHelper;
  change?: (payload: CheckboxSelectDefinitionChange) => void;
};

export type CheckboxSelectDefinitionValue = string[];

export type CheckboxSelectDefinitionValues = string[];

export type CheckboxSelectDefinitionLabels = string[];

export type CheckboxSelectDefinitionDisabled = boolean;

export type CheckboxSelectDefinitionRequired = boolean;

export type CheckboxSelectDefinitionHidden = boolean;

export type CheckboxSelectDefinitionLabel = string;

export type CheckboxSelectDefinitionHelper = string;

export type CheckboxSelectDefinitionChange = string[];
