/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type ContainerDefinitionProps = {
  maxWidth: ContainerDefinitionMaxWidth;
  fixed?: ContainerDefinitionFixed;
  disableGutters?: ContainerDefinitionDisableGutters;
};

export type ContainerDefinitionMaxWidth = 'xs' | 'sm' | 'md' | 'lg' | 'xl';

export type ContainerDefinitionFixed = boolean;

export type ContainerDefinitionDisableGutters = boolean;
