/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type FormDefinitionProps = {
  submitButtonText?: FormDefinitionSubmitButtonText;
  hiddenSubmitButton?: FormDefinitionHiddenSubmitButton;
  resetButtonText?: FormDefinitionResetButtonText;
  hiddenResetButton?: FormDefinitionHiddenResetButton;
  submit?: (payload: FormDefinitionSubmit) => void;
};

export type FormDefinitionSubmitButtonText = string;

export type FormDefinitionHiddenSubmitButton = boolean;

export type FormDefinitionResetButtonText = string;

export type FormDefinitionHiddenResetButton = boolean;

export interface FormDefinitionSubmit {
  [k: string]: unknown;
}
