/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type GridDefinitionProps = {
  columns: GridDefinitionColumns;
  breakpoints?: GridDefinitionBreakpoints;
};

export type GridDefinitionColumns = number;

export type GridDefinitionBreakpoints = {
  /**
   * 36em, 48em, 62em, 75em, 88em
   */
  breakpoint: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  columns: number;
}[];
