/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type GridDefinitionProps = {
  columns: GridDefinitionColumns;
  horizontalSpacing?: GridDefinitionHorizontalSpacing;
  verticalSpacing?: GridDefinitionVerticalSpacing;
};

export type GridDefinitionColumns = number;

export type GridDefinitionHorizontalSpacing = 'xs' | 'sm' | 'md' | 'lg' | 'xl';

export type GridDefinitionVerticalSpacing = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
