/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type GroupDefinitionProps = {
  direction: GroupDefinitionDirection;
  padding?: GroupDefinitionPadding;
  margin?: GroupDefinitionMargin;
};

export type GroupDefinitionDirection = 'horizontal' | 'vertical';

export type GroupDefinitionPadding = string;

export type GroupDefinitionMargin = string;
