/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type InputDefinitionProps = {
  type: InputDefinitionType;
  value?: InputDefinitionValue;
  placeholder?: InputDefinitionPlaceholder;
  disabled?: InputDefinitionDisabled;
  hidden?: InputDefinitionHidden;
  label?: InputDefinitionLabel;
  labelHidden?: InputDefinitionLabelHidden;
  labelPosition: InputDefinitionLabelPosition;
  labelWidth?: InputDefinitionLabelWidth;
  helper?: InputDefinitionHelper;
  change?: (payload: InputDefinitionChange) => void;
  enter?: (payload: InputDefinitionEnter) => void;
};

export type InputDefinitionType =
  | 'color'
  | 'date'
  | 'datetime-local'
  | 'email'
  | 'month'
  | 'number'
  | 'password'
  | 'tel'
  | 'text'
  | 'time'
  | 'url'
  | 'week';

export type InputDefinitionValue = string;

export type InputDefinitionPlaceholder = string;

export type InputDefinitionDisabled = boolean;

export type InputDefinitionHidden = boolean;

export type InputDefinitionLabel = string;

export type InputDefinitionLabelHidden = boolean;

export type InputDefinitionLabelPosition = 'left' | 'top';

export type InputDefinitionLabelWidth = string;

export type InputDefinitionHelper = string;

export type InputDefinitionChange = string;

export type InputDefinitionEnter = null;
