/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

import { ReactNode } from 'React';

export type InputDefinitionProps = {
  type:
    | 'color'
    | 'date'
    | 'datetime-local'
    | 'email'
    | 'month'
    | 'number'
    | 'password'
    | 'tel'
    | 'text'
    | 'time'
    | 'url'
    | 'week';
  value?: string;
  placeholder?: string;
  disabled?: boolean;
  readOnly?: boolean;
  hidden?: boolean;
  label?: string;
  labelCaption?: string;
  labelHidden?: boolean;
  labelPosition?: 'left' | 'top';
  labelAlignment?: 'left' | 'right';
  labelWidth?: string;
  tooltip?: string;
  helper?: string;
  spellCheck?: boolean;
  autofill?: boolean;
  change?: (payload: unknown) => void;
  enter?: (payload: unknown) => void;
  children?: ReactNode;
};
