/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type NumberInputDefinitionProps = {
  name?: NumberInputDefinitionName;
  placeholder?: NumberInputDefinitionPlaceholder;
  disabled?: NumberInputDefinitionDisabled;
  required?: NumberInputDefinitionRequired;
  label?: NumberInputDefinitionLabel;
  helper?: NumberInputDefinitionHelper;
};

export type NumberInputDefinitionName = string;

export type NumberInputDefinitionPlaceholder = string;

export type NumberInputDefinitionDisabled = boolean;

export type NumberInputDefinitionRequired = boolean;

export type NumberInputDefinitionLabel = string;

export type NumberInputDefinitionHelper = string;
