/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type RadioSelectDefinitionProps = {
  name?: RadioSelectDefinitionName;
  options: RadioSelectDefinitionOptions;
  disabled?: RadioSelectDefinitionDisabled;
  required?: RadioSelectDefinitionRequired;
  hidden?: RadioSelectDefinitionHidden;
  label?: RadioSelectDefinitionLabel;
  helper?: RadioSelectDefinitionHelper;
};

export type RadioSelectDefinitionName = string;

export type RadioSelectDefinitionOptions = {
  key: string;
  label: string;
}[];

export type RadioSelectDefinitionDisabled = boolean;

export type RadioSelectDefinitionRequired = boolean;

export type RadioSelectDefinitionHidden = boolean;

export type RadioSelectDefinitionLabel = string;

export type RadioSelectDefinitionHelper = string;
