/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type RadioSelectDefinitionProps = {
  value?: RadioSelectDefinitionValue;
  values?: RadioSelectDefinitionValues;
  labels?: RadioSelectDefinitionLabels;
  disabled?: RadioSelectDefinitionDisabled;
  required?: RadioSelectDefinitionRequired;
  hidden?: RadioSelectDefinitionHidden;
  label?: RadioSelectDefinitionLabel;
  helper?: RadioSelectDefinitionHelper;
  change?: (payload: RadioSelectDefinitionChange) => void;
};

export type RadioSelectDefinitionValue = string;

export type RadioSelectDefinitionValues = string[];

export type RadioSelectDefinitionLabels = string[];

export type RadioSelectDefinitionDisabled = boolean;

export type RadioSelectDefinitionRequired = boolean;

export type RadioSelectDefinitionHidden = boolean;

export type RadioSelectDefinitionLabel = string;

export type RadioSelectDefinitionHelper = string;

export type RadioSelectDefinitionChange = string | null;
