/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type SearchFormDefinitionProps = {
  submitButtonText?: SearchFormDefinitionSubmitButtonText;
  resetButtonText?: SearchFormDefinitionResetButtonText;
  submit?: (payload: SearchFormDefinitionSubmit) => void;
};

export type SearchFormDefinitionSubmitButtonText = string;

export type SearchFormDefinitionResetButtonText = string;

export interface SearchFormDefinitionSubmit {
  [k: string]: unknown;
}
