/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type SelectDefinitionProps = {
  name?: SelectDefinitionName;
  options: SelectDefinitionOptions;
  placeholder?: SelectDefinitionPlaceholder;
  disabled?: SelectDefinitionDisabled;
  required?: SelectDefinitionRequired;
  hidden?: SelectDefinitionHidden;
  label?: SelectDefinitionLabel;
  helper?: SelectDefinitionHelper;
};

export type SelectDefinitionName = string;

export type SelectDefinitionOptions = {
  key: string;
  label: string;
}[];

export type SelectDefinitionPlaceholder = string;

export type SelectDefinitionDisabled = boolean;

export type SelectDefinitionRequired = boolean;

export type SelectDefinitionHidden = boolean;

export type SelectDefinitionLabel = string;

export type SelectDefinitionHelper = string;
