/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

import { ReactNode } from 'React';

export type SelectDefinitionProps = {
  value?: string;
  values?: unknown[];
  labels?: unknown[];
  placeholder?: string;
  disabled?: boolean;
  hidden?: boolean;
  label?: string;
  labelHidden?: boolean;
  labelPosition?: 'left' | 'top';
  labelWidth?: string;
  helper?: string;
  change?: (payload: unknown) => void;
  children?: ReactNode;
};
