/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type SelectDefinitionProps = {
  value?: SelectDefinitionValue;
  values?: SelectDefinitionValues;
  labels?: SelectDefinitionLabels;
  placeholder?: SelectDefinitionPlaceholder;
  disabled?: SelectDefinitionDisabled;
  required?: SelectDefinitionRequired;
  hidden?: SelectDefinitionHidden;
  label?: SelectDefinitionLabel;
  helper?: SelectDefinitionHelper;
  change?: (payload: SelectDefinitionChange) => void;
};

export type SelectDefinitionValue = string;

export type SelectDefinitionValues = string[];

export type SelectDefinitionLabels = string[];

export type SelectDefinitionPlaceholder = string;

export type SelectDefinitionDisabled = boolean;

export type SelectDefinitionRequired = boolean;

export type SelectDefinitionHidden = boolean;

export type SelectDefinitionLabel = string;

export type SelectDefinitionHelper = string;

export type SelectDefinitionChange = string | null;
