/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

import { ReactNode } from 'React';

export type StackDefinitionProps = {
  direction: 'column-reverse' | 'column' | 'row-reverse' | 'row';
  divider?: boolean;
  spacing?: number;
  children?: ReactNode;
};
