/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type StackDefinitionProps = {
  direction: StackDefinitionDirection;
  divider: StackDefinitionDivider;
  spacing: StackDefinitionSpacing;
};

export type StackDefinitionDirection =
  | 'column-reverse'
  | 'column'
  | 'row-reverse'
  | 'row';

export type StackDefinitionDivider = boolean;

export type StackDefinitionSpacing = number;
