/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type TableDefinitionProps = {
  columns: TableDefinitionColumns;
  value: TableDefinitionValue;
};

export type TableDefinitionColumns = {
  label: string;
  type: 'text' | 'link';
  field: string;
  convertor?: string;
  link?: {
    screen?: string;
    search?: string;
  };
  disabledSorting?: boolean;
  /**
   * template
   */
  hiddenColumn?: string;
  /**
   * template
   */
  backgroundColor?: string;
}[];

export type TableDefinitionValue = {
  [k: string]: unknown;
}[];
