/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by SHUKUN.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run SHUKUN to regenerate this file.
 */

export type TextDefinitionProps = {
  value?: string;
  color: string;
  fontSize: string;
  fontStyle?: string;
  textAlign: string;
};
