import { Device } from './device.type';

export const devices: Device[] = [
  {
    name: 'phonePortrait',
    label: '手机竖版',
    width: '428px',
    height: '809px',
    top: '81px',
    right: '28px',
    bottom: '88px',
    left: '28px',
    background: 'phone-portrait.png',
  },
  {
    name: 'padPortrait',
    label: '平板竖版',
    width: '833px',
    height: '1153px',
    top: '76px',
    right: '56px',
    bottom: '76px',
    left: '56px',
    background: 'pad-portrait.png',
  },
  {
    name: 'padLandscape',
    label: '平板横版',
    width: '1153px',
    height: '833px',
    top: '56px',
    right: '76px',
    bottom: '56px',
    left: '76px',
    background: 'pad-landscape.png',
  },
  {
    name: 'notebook',
    label: '笔记本',
    width: '1440px',
    height: '100%',
    top: '42px',
    right: '0px',
    bottom: '0px',
    left: '0px',
    background: 'notebook.png',
  },
  {
    name: 'monitor',
    label: '显示器',
    width: '1920px',
    height: '100%',
    top: '42px',
    right: '0px',
    bottom: '0px',
    left: '0px',
    background: 'monitor.png',
  },
];
